"""PDF report generation + Slack broadcast (workflow #6)."""
from __future__ import annotations

from datetime import date, timedelta
from pathlib import Path
from typing import Any, Dict, Optional

import requests
from reportlab.graphics.charts.lineplots import LinePlot
from reportlab.graphics.shapes import Drawing
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle
from sqlalchemy import select
from sqlalchemy.orm import Session

from .config import settings
from .insights import ACTIONS, fmt
from .kpis import GROUP_ORDER, KPI_DEFS, day_values, series
from .models import Insight, Report

INK, MUTED, ACCENT = colors.HexColor("#2b1d14"), colors.HexColor("#7a6a5e"), colors.HexColor("#b5651d")
SEV = {"critical": colors.HexColor("#c0392b"), "warning": colors.HexColor("#d68910"),
       "info": colors.HexColor("#5d6d7e"), "good": colors.HexColor("#1e8449")}


def _safe(t: str) -> str:
    # reportlab's built-in fonts lack the rupee glyph
    return (t or "").replace("₹", "Rs ").replace("&", "&amp;").replace("<", "&lt;")


def build_pdf(s: Session, d: date) -> Path:
    cfg = settings()
    cfg.reports_dir.mkdir(parents=True, exist_ok=True)
    path = cfg.reports_dir / f"founderos-report-{d.isoformat()}.pdf"
    ss = getSampleStyleSheet()
    h1 = ParagraphStyle("h1", parent=ss["Title"], textColor=INK, fontSize=22, alignment=0, spaceAfter=2)
    h2 = ParagraphStyle("h2", parent=ss["Heading2"], textColor=ACCENT, fontSize=13, spaceBefore=14, spaceAfter=6)
    body = ParagraphStyle("b", parent=ss["BodyText"], textColor=INK, fontSize=10, leading=14)
    small = ParagraphStyle("s", parent=body, textColor=MUTED, fontSize=8.5)

    doc = SimpleDocTemplate(str(path), pagesize=A4, leftMargin=18 * mm, rightMargin=18 * mm,
                            topMargin=16 * mm, bottomMargin=16 * mm,
                            title=f"FounderOS daily report {d}", author="FounderOS")
    story = [Paragraph(f"FounderOS Daily Report", h1),
             Paragraph(_safe(f"{cfg.brand} · {d.strftime('%A, %d %B %Y')}"), small)]

    rows = s.execute(select(Insight).where(Insight.date == d).order_by(Insight.id)).scalars().all()
    summary = next((r for r in rows if r.kind == "summary"), None)
    if summary:
        story += [Paragraph("Executive summary", h2), Paragraph(_safe(summary.body), body)]

    # Revenue chart
    pts = series(s, "net_revenue", d - timedelta(days=29), d)
    if len(pts) > 2:
        dr = Drawing(170 * mm, 55 * mm)
        lp = LinePlot()
        lp.x, lp.y, lp.width, lp.height = 30, 15, 440, 130
        lp.data = [[(i, v / 1000) for i, (_, v) in enumerate(pts)]]
        lp.lines[0].strokeColor, lp.lines[0].strokeWidth = ACCENT, 1.8
        lp.xValueAxis.visible = False
        lp.yValueAxis.labels.fontSize = 7
        lp.yValueAxis.labelTextFormat = "%d"
        dr.add(lp)
        story += [Paragraph("Net revenue, last 30 days (Rs thousands)", h2), dr]

    # KPI table
    today = day_values(s, d)
    for grp in GROUP_ORDER:
        ks = [k for k in KPI_DEFS if k.group == grp and k.key in today]
        if not ks:
            continue
        data = [[grp, "Value", "7-day avg"]]
        for k in ks:
            prev = [v for _, v in series(s, k.key, d - timedelta(days=7), d - timedelta(days=1))]
            base = sum(prev) / len(prev) if prev else None
            data.append([k.label, _safe(fmt(k.unit, today[k.key])), _safe(fmt(k.unit, base)) if base is not None else "-"])
        t = Table(data, colWidths=[85 * mm, 45 * mm, 40 * mm])
        t.setStyle(TableStyle([
            ("FONTSIZE", (0, 0), (-1, -1), 8.5), ("TEXTCOLOR", (0, 0), (-1, 0), ACCENT),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"), ("TEXTCOLOR", (0, 1), (-1, -1), INK),
            ("ALIGN", (1, 0), (-1, -1), "RIGHT"), ("LINEBELOW", (0, 0), (-1, 0), 0.6, ACCENT),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#faf5ef")]),
            ("TOPPADDING", (0, 0), (-1, -1), 3), ("BOTTOMPADDING", (0, 0), (-1, -1), 3)]))
        story += [Spacer(1, 6), t]

    # Insights
    issues = [r for r in rows if r.kind == "anomaly"]
    if issues:
        story.append(Paragraph("Anomalies &amp; recommended actions", h2))
        for r in issues:
            sty = ParagraphStyle("t", parent=body, textColor=SEV.get(r.severity, INK), fontName="Helvetica-Bold")
            story.append(Paragraph(f"{r.severity.upper()} · {_safe(r.title)}", sty))
            story.append(Paragraph(_safe(r.body), body))
            if r.action:
                story.append(Paragraph(f"<b>Action:</b> {_safe(r.action)}", body))
            story.append(Spacer(1, 6))
    story.append(Paragraph(f"Generated by FounderOS · insights by "
                           f"{'OpenAI' if summary and summary.origin == 'ai' else 'rules engine'}", small))
    doc.build(story)
    return path


# ---------- Slack ----------
def _slack_upload(path: Path, comment: str) -> str:
    cfg = settings()
    h = {"Authorization": f"Bearer {cfg.slack_bot_token}"}
    r = requests.post("https://slack.com/api/files.getUploadURLExternal", headers=h, timeout=30,
                      data={"filename": path.name, "length": path.stat().st_size}).json()
    if not r.get("ok"):
        raise RuntimeError(f"getUploadURLExternal: {r.get('error')}")
    requests.post(r["upload_url"], data=path.read_bytes(), timeout=60).raise_for_status()
    r2 = requests.post("https://slack.com/api/files.completeUploadExternal", headers=h, timeout=30, json={
        "files": [{"id": r["file_id"], "title": path.stem}], "channel_id": cfg.slack_channel_id,
        "initial_comment": comment}).json()
    if not r2.get("ok"):
        raise RuntimeError(f"completeUploadExternal: {r2.get('error')}")
    return "sent_pdf"


def broadcast(s: Session, d: date, path: Path) -> str:
    cfg = settings()
    summary = s.execute(select(Insight).where(Insight.date == d, Insight.kind == "summary")).scalar_one_or_none()
    crit = s.execute(select(Insight).where(Insight.date == d, Insight.kind == "anomaly",
                                           Insight.severity.in_(["critical", "warning"]))).scalars().all()
    lines = [f"*FounderOS · {cfg.brand} · {d.strftime('%d %b %Y')}*", summary.body if summary else ""]
    for i in crit[:4]:
        lines.append(f"{'🔴' if i.severity == 'critical' else '🟠'} *{i.title}* — {i.action or i.body}")
    text = "\n".join(l for l in lines if l)
    try:
        if cfg.slack_bot_token and cfg.slack_channel_id:
            status = _slack_upload(path, text)
        elif cfg.slack_webhook_url:
            requests.post(cfg.slack_webhook_url, json={"text": text}, timeout=30).raise_for_status()
            status = "sent_text"
        else:
            status = "dry_run"  # no Slack configured; the PDF is still saved locally
    except Exception as exc:
        status = f"error: {exc}"[:60]
    rep = s.execute(select(Report).where(Report.date == d)).scalar_one_or_none()
    if rep is None:
        rep = Report(date=d, path=str(path))
        s.add(rep)
    rep.path, rep.slack_status = str(path), status
    s.flush()
    return status
